language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    recipients:
      - yosuke.matsusaka@gmail.com
    on_success: change
    on_failure: always
sudo: required
dist: trusty
before_install:
  - export ROS_DISTRO=indigo
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo add-apt-repository ppa:hrg/daily -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-tools python-rosdep python-wstool python-setuptools openhrp meshlab imagemagick python-omniorb openrtm-aist-python python-numpy
  - sudo easy_install pip
  - sudo pip install --upgrade pip
  - sudo pip install enum34
  - sudo pip install catkin_pkg
  - sudo rosdep init
  - rosdep update
install:
  - mkdir -p ~/ros/ws_$REPOSITORY_NAME/src
  - cd ~/ros/ws_$REPOSITORY_NAME/src
  - wstool init . $CI_SOURCE_PATH/.rosinstall
  - rm -rf $REPOSITORY_NAME
  - ln -s $CI_SOURCE_PATH .
  - cd ../
  - catkin init
  - catkin config --install
  - rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
  - cd ~/
  - git clone https://github.com/fkanehiro/simtrans.git
  - cd simtrans
  - sudo pip install -r requirements.txt
  - sudo python setup.py install
  - cd ../
before_script:
  - source /opt/ros/$ROS_DISTRO/setup.bash  
script:
  - cd ~/ros/ws_$REPOSITORY_NAME
  - catkin build -p 1 -v choreonoid_ros_pkg
